//
//  History.swift
//  Magpie
//

import Foundation
import Cocoa

/// Representation of all the history
class History {

    private var _items = [HistoryItem]()

    /// The last change count for which the items on the pasteboard have been added to the history. Saved so copies aren't re-added after relaunching.
    private(set) var lastRecordedChangeCount = -1 {
        didSet { Settings.main.pasteboardChangeCount = lastRecordedChangeCount }
    }
    
    /// The file manager for the storage of pasteboard history.
    var historyFM: HistoryFileManager

    /// The store for item metadata (copy time, source app, pinned state, recognised text).
    var metadataStore: HistoryMetadataStore

    /// The cache for the history item.
    var cache: HistoryCache

    /// The most unpinned items kept. Pinned items don't count towards it.
    private(set) var maxItems: Int

    var items: [HistoryItem] {
        get {
            return self._items
        }
    }

    enum Change {
        case initial
        case insert(index: Int)
        case delete(deletedItem: HistoryItem)
        case clear
        case move(from: Int, to: Int)
        case itemLimitDecreased(deletedItems: [HistoryItem])
        /// The item's metadata changed, e.g. it was pinned or its text was recognised.
        case update(index: Int)
    }

    typealias SubscribeHandler = ([HistoryItem], Change) -> Void
    private var subscribers = [SubscribeHandler]()

    /// Copies made while one of these apps is frontmost are not saved.
    var excludedBundleIds = Set<String>()

    /// If a pasteboard item's types contains any of these, it will not be saved.
    private let pasteboardTypeDenylist: Set = [
        "org.nspasteboard.TransientType",
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
        "com.typeit4me.clipping",
        "de.petermaurer.TransientPasteboardType",
        "Pasteboard generator type",
        "net.antelle.keeweb",
    ]
    /// These pasteboard item types will not be saved.
    private let pasteboardTypeIgnoreList = Set([
        "dyn.ah62d4rv4gu8zg55zsmv0nvperf4g86varvu0635zqfx0nkdsqf00nkduqf31k3pcr7u1e3basv61a3k",
    ].map({NSPasteboard.PasteboardType(rawValue: $0)}));

    init(historyFM: HistoryFileManager = .default, metadataStore: HistoryMetadataStore = .default, cache: HistoryCache, items: [HistoryItem], maxItems: Int = Constants.system.maxHistoryItems) {
        self.historyFM = historyFM
        self.metadataStore = metadataStore
        self.cache = cache
        self._items = items
        self.maxItems = maxItems

        if unpinnedCount > maxItems {
            reduceHistory(to: maxItems)
        }
    }

    static func load(historyFM: HistoryFileManager = .default, cache: HistoryCache) -> History {
        let history = historyFM.loadHistory(cache: cache)
        history.restoreMetadata()
        return history
    }

    /// Applies saved metadata to the loaded items. Items saved before metadata existed use their folder's creation date.
    private func restoreMetadata() {
        let stored = metadataStore.load()
        for item in _items {
            if let metadata = stored[item.fsId] {
                item.metadata = metadata
            }
            else {
                let path = historyFM.getUrl(forItemWithId: item.fsId).path
                let created = (try? FileManager.default.attributesOfItem(atPath: path))?[.creationDate] as? Date
                item.metadata = HistoryItemMetadata(copiedAt: created ?? Date())
            }
        }
        metadataStore.save(_items)
    }

    func subscribe(onNext: @escaping SubscribeHandler) {
        subscribers.append(onNext)
        onNext(_items, Change.initial)
    }

    private func notify(_ change: Change) {
        subscribers.forEach({$0(_items, change)})
    }

    private var unpinnedCount: Int {
        return _items.reduce(0, { $0 + ($1.metadata.isPinned ? 0 : 1) })
    }

    func insertItem(_ item: HistoryItem, at i: Int) {
        _items.insert(item, at: i)
        notify(.insert(index: i))
        historyFM.insertItem(newHistory: _items, at: i)
        metadataStore.save(_items)

        if unpinnedCount > maxItems {
            reduceHistory(to: maxItems)
        }
    }

    func deleteItem(at i: Int) {
        let removed = _items.remove(at: i)
        notify(.delete(deletedItem: removed))
        historyFM.deleteItem(newHistory: _items, deleted: removed)
        metadataStore.save(_items)
    }

    func clear() {
        // Pinned items survive clearing the history.
        let pinned = _items.filter({ $0.metadata.isPinned })
        if pinned.isEmpty {
            _items.forEach({$0.stopCaching()})
            _items = []
            notify(.clear)
            historyFM.clearHistory()
        }
        else {
            let removed = _items.filter({ !$0.metadata.isPinned })
            _items = pinned
            notify(.itemLimitDecreased(deletedItems: removed))
            historyFM.deleteItems(newHistory: _items, deleted: removed)
        }
        metadataStore.save(_items)
    }

    func moveItem(at i: Int, to j: Int) {
        let item = _items.remove(at: i)
        _items.insert(item, at: j)
        notify(.move(from: i, to: j))
        historyFM.moveItem(newHistory: _items, from: i, to: j)
    }

    func setPinned(_ isPinned: Bool, forItemAt i: Int) {
        guard _items[i].metadata.isPinned != isPinned else { return }
        _items[i].metadata.isPinned = isPinned
        notify(.update(index: i))
        metadataStore.save(_items)

        if !isPinned && unpinnedCount > maxItems {
            reduceHistory(to: maxItems)
        }
    }

    func setRecognizedText(_ text: String, for item: HistoryItem) {
        guard let i = _items.firstIndex(of: item) else { return }
        item.metadata.recognizedText = text
        notify(.update(index: i))
        metadataStore.save(_items)
    }

    func recordPasteboardChange(withCount changeCount: Int) {
        lastRecordedChangeCount = changeCount
    }

    func setMaxItems(_ maxItems: Int) {
        if maxItems < self.maxItems {
            reduceHistory(to: maxItems)
        }
        self.maxItems = maxItems
        Settings.main.maxHistory = maxItems
    }

    /// Removes the oldest unpinned items until there are at most `maxItems` unpinned items.
    private func reduceHistory(to maxItems: Int) {
        var excess = unpinnedCount - maxItems
        guard excess > 0 else {
            return;
        }
        var deletedItems = [HistoryItem]()
        for i in _items.indices.reversed() where excess > 0 && !_items[i].metadata.isPinned {
            deletedItems.append(_items.remove(at: i))
            excess -= 1
        }
        historyFM.deleteItems(newHistory: _items, deleted: deletedItems)
        metadataStore.save(_items)
        notify(.itemLimitDecreased(deletedItems: deletedItems))
    }

    /// Recognises text in image items that haven't been processed yet, one at a time in the background.
    func recognizeTextInExistingImages() {
        let pending = _items.filter({ $0.kind == .image && $0.metadata.recognizedText == nil })
        Task { @MainActor in
            for item in pending {
                guard let text = await TextRecognizer.recognizeText(in: item) else { continue }
                setRecognizedText(text, for: item)
            }
        }
    }
}

extension History: PasteboardMonitorDelegate {

    func pasteboardDidChange(_ pasteboard: NSPasteboard, originBundleId: String?) {
        // Check if we made this pasteboard change, if so, ignore
        if pasteboard.changeCount == lastRecordedChangeCount {
            return
        }

        // Save pasteboard change count
        defer { recordPasteboardChange(withCount: pasteboard.changeCount) }

        if let origin = originBundleId, excludedBundleIds.contains(origin) {
            return
        }

        // Check there are items on the pasteboard
        guard let items = pasteboard.pasteboardItems else {
            return
        }

        for item in items {
            let filteredTypes = Set(item.types).subtracting(self.pasteboardTypeIgnoreList)
            let hasTypes = !filteredTypes.isEmpty
            let hasNoDeniedTypes = Set(filteredTypes.map({ $0.rawValue })).isDisjoint(with: pasteboardTypeDenylist)

            if hasTypes && hasNoDeniedTypes {
                var data = [NSPasteboard.PasteboardType: Data]()
                for type in filteredTypes {
                    if let d = item.data(forType: type) {
                        let firstData = self._items.first?.data(forType: type)
                        let isNewData = firstData == nil || firstData?.hashValue != d.hashValue
                        if isNewData {
                            data[type] = d
                        }
                    }
                    else {
                        print("Warning: new pasteboard data nil for type '\(type.rawValue)'")
                    }
                }
                if !data.isEmpty {
                    let historyItem = HistoryItem(unsavedData: data, cache: cache)
                    historyItem.metadata = HistoryItemMetadata(copiedAt: Date(), sourceBundleId: originBundleId)
                    insertItem(historyItem, at: 0)

                    if historyItem.kind == .image {
                        Task { @MainActor in
                            if let text = await TextRecognizer.recognizeText(in: historyItem) {
                                self.setRecognizedText(text, for: historyItem)
                            }
                        }
                    }
                }
            }
        }
    }
}
