//
//  History.swift
//  Magpie
//

import Foundation
import Cocoa
import SwiftData

/// All of the clipboard history, most recent first, stored with SwiftData.
///
/// `items` mirrors the stored `ClipItem`s ordered by position. Every change is saved immediately and reported to subscribers, which use the `Change` to keep their selection stable.
class History {

    private var _items = [HistoryItem]()

    var items: [HistoryItem] {
        return _items
    }

    let context: ModelContext

    /// The last change count for which the items on the pasteboard have been added to the history. Saved so copies aren't re-added after relaunching.
    private(set) var lastRecordedChangeCount = -1 {
        didSet { if persistsSettings { Settings.main.pasteboardChangeCount = lastRecordedChangeCount } }
    }

    /// The most unpinned items kept. Pinned items don't count towards it.
    private(set) var maxItems: Int

    /// Whether changes to the change count and limit are written to `Settings`. Off for tests.
    private let persistsSettings: Bool

    enum Change {
        case initial
        case insert(index: Int)
        case delete(deletedItem: HistoryItem)
        case clear
        case move(from: Int, to: Int)
        case itemLimitDecreased(deletedItems: [HistoryItem])
        /// The item's metadata changed, e.g. it was pinned or its text was recognised.
        case update(index: Int)
    }

    typealias SubscribeHandler = ([HistoryItem], Change) -> Void
    private var subscribers = [SubscribeHandler]()

    /// Copies made while one of these apps is frontmost are not saved.
    var excludedBundleIds = Set<String>()

    /// If a pasteboard item's types contains any of these, it will not be saved.
    private let pasteboardTypeDenylist: Set = [
        "org.nspasteboard.TransientType",
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
        "com.typeit4me.clipping",
        "de.petermaurer.TransientPasteboardType",
        "Pasteboard generator type",
        "net.antelle.keeweb",
    ]
    /// These pasteboard item types will not be saved.
    private let pasteboardTypeIgnoreList = Set([
        "dyn.ah62d4rv4gu8zg55zsmv0nvperf4g86varvu0635zqfx0nkdsqf00nkduqf31k3pcr7u1e3basv61a3k",
    ].map({NSPasteboard.PasteboardType(rawValue: $0)}));


    // MARK: - Loading

    init(container: ModelContainer, maxItems: Int = Constants.system.maxHistoryItems, persistsSettings: Bool = true) {
        self.context = ModelContext(container)
        self.context.autosaveEnabled = false
        self.maxItems = maxItems
        self.persistsSettings = persistsSettings

        do {
            let models = try context.fetch(FetchDescriptor<ClipItem>(sortBy: [SortDescriptor(\.position, order: .reverse)]))
            // Items analysed by an older analyser (or before analysis existed) are analysed again.
            let outdated = models.filter({ $0.analysisVersion < ClipAnalyzer.version })
            for model in outdated {
                model.apply(ClipAnalyzer.analyze(model.pasteboardData))
            }
            if !outdated.isEmpty {
                try context.save()
            }
            _items = models.map(HistoryItem.init(model:))
        }
        catch {
            MagpieError(localizedDescription: "Failed to load the history: \(error.localizedDescription)").log(with: ErrorLogger.general)
        }
    }

    /// Opens the history saved on disk. If the store can't be opened, the history is kept in memory for this session.
    static func load() -> History {
        do {
            return History(container: try HistoryStore.makeContainer())
        }
        catch {
            let historyError = MagpieError(localizedDescription: "Your clipboard history couldn't be opened, so this session's history won't be saved. \(error.localizedDescription)")
            historyError.log(with: ErrorLogger.general)
            historyError.show(with: Alerter.general)
            return History(container: try! HistoryStore.makeContainer(inMemory: true))
        }
    }

    func subscribe(onNext: @escaping SubscribeHandler) {
        subscribers.append(onNext)
        onNext(_items, Change.initial)
    }

    private func notify(_ change: Change) {
        subscribers.forEach({$0(_items, change)})
    }

    private func save() {
        do {
            try context.save()
        }
        catch {
            MagpieError(localizedDescription: "Failed to save the history: \(error.localizedDescription)").log(with: ErrorLogger.general)
        }
    }

    private var unpinnedCount: Int {
        return _items.reduce(0, { $0 + ($1.isPinned ? 0 : 1) })
    }


    // MARK: - Changes

    /// Adds new pasteboard data to the top of the history.
    @discardableResult
    func insert(data: [NSPasteboard.PasteboardType: Data], copiedAt: Date = Date(), sourceBundleId: String?) -> HistoryItem {
        let model = HistoryItem.makeModel(data: data, position: (_items.first?.model.position ?? 0) + 1, copiedAt: copiedAt, sourceBundleId: sourceBundleId)
        context.insert(model)
        let item = HistoryItem(model: model)
        _items.insert(item, at: 0)
        save()
        notify(.insert(index: 0))

        if unpinnedCount > maxItems {
            reduceHistory(to: maxItems)
        }
        return item
    }

    func deleteItem(at i: Int) {
        let removed = _items.remove(at: i)
        delete([removed])
        save()
        notify(.delete(deletedItem: removed))
    }

    /// Deletes specific items, e.g. the largest ones from the Storage settings.
    func delete(items toDelete: [HistoryItem]) {
        let ids = Set(toDelete.map(\.id))
        let removed = _items.filter({ ids.contains($0.id) })
        guard !removed.isEmpty else { return }
        _items.removeAll(where: { ids.contains($0.id) })
        delete(removed)
        save()
        notify(.itemLimitDecreased(deletedItems: removed))
    }
    
    /// Removes everything except pinned items.
    func clear() {
        let removed = _items.filter({ !$0.isPinned })
        _items.removeAll(where: { !$0.isPinned })
        delete(removed)
        save()
        notify(_items.isEmpty ? .clear : .itemLimitDecreased(deletedItems: removed))
    }

    func moveItem(at i: Int, to j: Int) {
        let item = _items.remove(at: i)
        _items.insert(item, at: j)
        item.model.position = position(forItemAt: j)
        save()
        notify(.move(from: i, to: j))
    }

    func setPinned(_ isPinned: Bool, forItemAt i: Int) {
        guard _items[i].isPinned != isPinned else { return }
        _items[i].isPinned = isPinned
        save()
        notify(.update(index: i))

        if !isPinned && unpinnedCount > maxItems {
            reduceHistory(to: maxItems)
        }
    }

    func setRecognizedText(_ text: String, for item: HistoryItem) {
        guard let i = _items.firstIndex(of: item) else { return }
        item.recognizedText = text
        save()
        notify(.update(index: i))
    }

    func recordPasteboardChange(withCount changeCount: Int) {
        lastRecordedChangeCount = changeCount
    }

    func setMaxItems(_ maxItems: Int) {
        if maxItems < self.maxItems {
            reduceHistory(to: maxItems)
        }
        self.maxItems = maxItems
        if persistsSettings {
            Settings.main.maxHistory = maxItems
        }
    }


    // MARK: - Helpers

    /// Deletes the items' models. Marks them removed first, so any UI still holding them stops reading their data.
    private func delete(_ items: [HistoryItem]) {
        for item in items {
            item.isRemoved = true
            context.delete(item.model)
        }
    }

    /// Chooses a position for the item at `index` between its neighbours in `_items`.
    private func position(forItemAt index: Int) -> Double {
        let above = index > 0 ? _items[index - 1].model.position : nil
        let below = index < _items.count - 1 ? _items[index + 1].model.position : nil
        switch (above, below) {
        case (nil, nil):
            return 0
        case (nil, let below?):
            return below + 1
        case (let above?, nil):
            return above - 1
        case (let above?, let below?):
            let middle = (above + below) / 2
            // Repeated moves between the same neighbours eventually exhaust Double precision; spread everything out again.
            if middle <= below || middle >= above {
                renumberPositions()
                return _items[index].model.position
            }
            return middle
        }
    }

    private func renumberPositions() {
        for (i, item) in _items.enumerated() {
            item.model.position = Double(_items.count - i)
        }
    }

    /// Removes the oldest unpinned items until there are at most `maxItems` unpinned items.
    private func reduceHistory(to maxItems: Int) {
        var excess = unpinnedCount - maxItems
        guard excess > 0 else {
            return;
        }
        var deletedItems = [HistoryItem]()
        for i in _items.indices.reversed() where excess > 0 && !_items[i].isPinned {
            deletedItems.append(_items.remove(at: i))
            excess -= 1
        }
        delete(deletedItems)
        save()
        notify(.itemLimitDecreased(deletedItems: deletedItems))
    }

    /// Recognises text in image items that haven't been processed yet, one at a time in the background.
    func recognizeTextInExistingImages() {
        let pending = _items.filter({ $0.kind == .image && $0.recognizedText == nil })
        Task { @MainActor in
            for item in pending where !item.isRemoved {
                guard let text = await TextRecognizer.recognizeText(in: item) else { continue }
                setRecognizedText(text, for: item)
            }
        }
    }
}

extension History: PasteboardMonitorDelegate {

    func pasteboardDidChange(_ pasteboard: NSPasteboard, originBundleId: String?) {
        // Check if we made this pasteboard change, if so, ignore
        if pasteboard.changeCount == lastRecordedChangeCount {
            return
        }

        // Save pasteboard change count
        defer { recordPasteboardChange(withCount: pasteboard.changeCount) }

        if let origin = originBundleId, excludedBundleIds.contains(origin) {
            return
        }

        // Check there are items on the pasteboard
        guard let items = pasteboard.pasteboardItems else {
            return
        }

        for item in items {
            let filteredTypes = Set(item.types).subtracting(self.pasteboardTypeIgnoreList)
            let hasTypes = !filteredTypes.isEmpty
            let hasNoDeniedTypes = Set(filteredTypes.map({ $0.rawValue })).isDisjoint(with: pasteboardTypeDenylist)

            if hasTypes && hasNoDeniedTypes {
                var data = [NSPasteboard.PasteboardType: Data]()
                for type in filteredTypes {
                    if let d = item.data(forType: type) {
                        let firstData = self._items.first?.data(forType: type)
                        let isNewData = firstData == nil || firstData != d
                        if isNewData {
                            data[type] = d
                        }
                    }
                    else {
                        print("Warning: new pasteboard data nil for type '\(type.rawValue)'")
                    }
                }
                if !data.isEmpty {
                    let historyItem = insert(data: data, sourceBundleId: originBundleId)

                    if historyItem.kind == .image {
                        Task { @MainActor in
                            if let text = await TextRecognizer.recognizeText(in: historyItem) {
                                self.setRecognizedText(text, for: historyItem)
                            }
                        }
                    }
                }
            }
        }
    }
}
